# Generated by Django 4.0.6 on 2022-07-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_section_section_article_section_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='name',
            new_name='scopes',
        ),
    ]
