# Generated by Django 4.0.6 on 2022-07-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_name_section_scopes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='scopes',
            new_name='name',
        ),
    ]
