# Generated by Django 4.0.6 on 2022-07-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_scope_scope_aricle_remove_section_article_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='name',
            new_name='is_main',
        ),
    ]
