# Generated by Django 4.0.6 on 2022-07-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_name_scope_is_main'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='is_main',
            new_name='name',
        ),
    ]
