# Generated by Django 4.0.6 on 2022-07-28 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_rename_name_scope_tag_name_remove_article_scope_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope_aricle',
            options={'verbose_name': 'раздел для статьи', 'verbose_name_plural': 'Тематика статьи'},
        ),
        migrations.RenameField(
            model_name='scope',
            old_name='tag_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(through='articles.Scope_Aricle', to='articles.scope'),
        ),
        migrations.AlterField(
            model_name='scope_aricle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scope_aricle',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Основной'),
        ),
        migrations.AlterField(
            model_name='scope_aricle',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.scope', verbose_name='Раздел'),
        ),
    ]
