# Generated by Django 4.0.6 on 2022-07-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_scope_aricle_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scope_Aricle',
            new_name='Tabel',
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={},
        ),
        migrations.RenameField(
            model_name='tabel',
            old_name='scope',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='scope',
        ),
        migrations.AddField(
            model_name='scope',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.Tabel', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
