# Generated by Django 4.0.6 on 2022-07-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_rename_tabel_scope_aricle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope_aricle',
            old_name='scope',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='articles',
        ),
        migrations.AddField(
            model_name='article',
            name='scope',
            field=models.ManyToManyField(related_name='tags', through='articles.Scope_Aricle', to='articles.scope'),
        ),
    ]
