# Generated by Django 4.0.6 on 2022-07-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_rename_scope_scope_aricle_tag_remove_scope_articles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
    ]
